DFR-975: resolve vul
hmcts/finrem-notification-service pull request #271
Opened 2022-04-07 09:43 UTC by rishikrsharma

### JIRA link (if applicable) ###
DFR-975

### Change description ###
resolve spring dependency

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2022-04-07 09:51 UTC, JohnnyVineall requested changes
line 117 -> //CVE-2022-22965

2022-04-07 09:55 UTC, rishikrsharma commented
> line 117 -> //[CVE-2022-22965](https://github.com/advisories/GHSA-36p3-wjmg-h94x)

done

2022-04-07 11:10 UTC, JohnnyVineall approved these changes

2022-04-07 11:19 UTC, ruban72 approved these changes

2022-04-11 10:32 UTC, EllisD-B approved these changes

2022-04-12 08:39 UTC, BWeeks-JusticeGovUK approved these changes

2022-04-12 10:31 UTC, arun-hmcts approved these changes

2022-04-12 10:31 UTC, merged